name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag summerhoax
    - name: Login to registry
      run: docker login -u admin -p ${{ secrets.PASSWORD }} registry.plox.host
    - name: Tag Images
      run: docker tag summerhoax registry.plox.host/mark/sh-site:latest
    - name: Push Images
      run: docker push registry.plox.host/mark/sh-site:latest
